### ISSUE TITLE
Enable an ENV value for retrom webclient docker to retrom backend

### ISSUE THREAD

**Issue by mylesvarns** [JMBeresford/retrom#118]
I have setup a docker compose file that will start both the retrom backend and retrom web client on my homelab. Once I go to the web client and enter in the retrom backend URL, it connects and works as one would expect. However, if I clear cache, access the web client via my phone or other device, or update the retrom web docker image, then the value that I entered for the retrom backend target is cleared out. This makes sense as the container data is volatile and non persistent. 

This is undesirable for those of us who have only one backend target URL and would prefer to have it persist across reboots or when viewing the web client on multiple devices. I propose that one or both options be available:

1. Enable an ENV value that can be used to inform the container of the retrom backend target URL through the docker compose file like the below snippet.

Services:
.....
Environment:
  - RETROM_BACKEND=http://host:5101
.....

2. Have a config.json file for the web client container, similar to the retrom backend container, that can be bound to the host where the value is stored like below.

{
  "retrom":{
    "backend_url": "http://host:5101"
  }
}

If the webclient could be included by default with the backend image, resulting in 1 image instead of 2 separate images, and be hard coded to the target by default that would be great as well.

**Comment by JMBeresford** [comment]
There currently [is an env var](https://github.com/JMBeresford/retrom/blob/34a3d729fc7befde745a0d3469eb62274ab7df7b/docker/web.Dockerfile#L36) that can be set which will determine the _default value_, however the web-based client stores it's config in localstorage and is therefore per-browser. This is because the web-client is currently just static files, meaning any and all requests sent to the backend service _originate from the browser currently using the web-client_. This means that the url for the service that you type into the web client needs to be accessible from that browser being used.

The web client currently does not communicate directly w/ the backend within their container bounds, and so the behavior you are asking for is not currently possible.

It is planned for the web client to be updated to use node.js locally to implement this soon, and will additionally be optionally bundled w/ the service to make this much more of a seamless experience. Until then, the current restrictions will unfortunately remain as is.

You can follow #119 for progress on this.
