### ISSUE TITLE
UI Bug with games / folders with . (dot) in the name

### ISSUE THREAD

**Issue by Kimbaras** [JMBeresford/retrom#127]
Hey there!

First of all, nice work! Looks really promising and looking forward for future developments on this one!

Then the ugly... testing it with my local game library I've found a little UI bug when the game folder cointains a . (dot) character.

I'm currently using a single library in the config.json file, configured as a "Multi-File Games" structure, all is working pretty good expect for some title which as mentioned have a dot in the name.
I've found it in the web client, didn't test (yet) the client as I don't really plan to use it, but I may give it a try later on.

An example in the screens

From the webui
![ui bug](https://github.com/user-attachments/assets/facecbbf-3aa9-4df3-b57f-e853dcc7f7db)

From the filesystem
![filesystem](https://github.com/user-attachments/assets/67220eb9-305c-474b-b213-aec2d3caacfe)

But the same applies also for different titles, I'm getting the same results also for the following titles:

- F.3.A.R
- F.E.A.R
- F.E.A.R. - Extraction Point
- F.E.A.R. - Perseus Mandate
- H.A.W.X 2

As you can see from the screens, it seems the issue is related to the dot, as the other characters are properly displayed.

Thanks!

**Comment by JMBeresford** [comment]
Thank you for the praise! I hope the development of Retrom serves you well 😎 

Regarding the issue, yes, this is something I have been wrestling with for a while. The reason for this is due to some rom types / emulators having optional compound file extensions ( e.g. `.xiso.iso` for Xbox  dumps converted to the `xiso` format ). As such, where to determine a file-name should be split and considered `name` vs `extension` becomes ambiguous.

With the official addition of single file game support, however, I think we can safely assume periods belong in the name _if_ the entry is known to be a directory. I'll get this whipped up soon.

Note that for single-file game entries, this behavior will remain for the reasoning described above. Those will need to be manually addressed in the client (see screenshots). Eventually I'll likely add optional parameter to the `content_directories` entries in the config to allow the user to select the desired behavior from the available strategies.

![Screenshot 2024-09-26 at 9 41 37 AM](https://github.com/user-attachments/assets/4f2ccb61-b704-43b1-9898-8221c3a56281)
![Screenshot 2024-09-26 at 9 43 21 AM](https://github.com/user-attachments/assets/71e3485a-99b5-4d7a-a049-84be64d41b12)

**Comment by JMBeresford** [comment]
@Kimbaras I should also mention that the filename/path is only used here as a fallback if the game has yet been matched to any metadata. Once there is a `metadata.name` entry ( generally via `Library > Download Metadata` menu item ) that will instead be used.

**Comment by JMBeresford** [comment]
I flip flopped on my stance on this again. I think it will be less common for users to have compound file extensions, and the visual artifact of something like that is less jarring than what you have here. Additionally, nointro and similar conventions dictate periods belong in rom filenames, so Retrom will now unconditionally split the extension off at the final `.`.

@Kimbaras This should be fixed in Retrom 0.1.7 which should be live in the hour.
