### ISSUE TITLE
Pre-released are cluttering release timeline

### ISSUE THREAD

**Issue by cstby** [JMBeresford/retrom#191]
After the recent changes to the GitHub Actions workflow, anyone subscribed to the releases feed is getting a large number of notifications for pre-releases.

**Comment by JMBeresford** [comment]
This is unfortunately a common issue w/ release visibility+announcements on github. It is not possible to subscribe to *only* regular releases, so if you want notifications for the release cycle you must also get notified for prereleases.

This is in direct conflict w/ the fact that draft releases cannot be made public. This means that the only way for me to distribute debug/prerelease builds to users is via prereleases. I'm sorry that this is causing your timeline to be cluttered, but outside of configuring an entire new distribution process my hands are tied.

You could always rely on release notifications via the [discord server](https://discord.gg/tM7VgWXCdZ) instead, if you prefer. Those announcements do not include prereleases.

I will continue to think on a way to mitigate this issue, and I'm open to suggestions in the case that perhaps I have overlooked something. However, I will be closing this due to my reasoning above.
