### ISSUE TITLE
retrom web client not working with reverse proxy (npm)

### ISSUE THREAD

**Issue by Toomblr** [JMBeresford/retrom#96]
Hi!

When I reach retrom web client via my reverse proxy (nginx proxy manager) / FQDN. It won't connect to the server.
However when I reach web client via IP:3000, setup is successful. 
<img width="587" alt="Screenshot 2024-09-16 at 17 45 14" src="https://github.com/user-attachments/assets/18a4b0c0-bb99-4dd0-ab16-3111d97181ba">

I tried different browsers (Chrome / Firefox). Also tried disabling caching assets and blocking common exploits in NPM.
<img width="482" alt="Screenshot 2024-09-16 at 17 47 51" src="https://github.com/user-attachments/assets/23ef272e-ac84-45db-8788-86171e91b066">

Any clues?

**Comment by JMBeresford** [comment]
Hm, could you provide the following for me:

1. retrom-web container logs
2. nginx block for the route you are using, and any other nginx config you think might be relevant
3. nginx logs

**Comment by jquinn96** [comment]
Hi @Toomblr,

I'm assuming that when you access the web client via NPM, it's HTTPS? If so, the HTTP request to the Retrom backend will be blocked by your browser due to mixed content.

I believe you should be able to put the Retrom backend behind NPM too (the API appears to just be a web service from my investigations so far) at say retrom-api.domain.name and then point web client at https://retrom-api.domain.name:443

This has worked for me so far with Cloudflare Tunnels. 

Cheers

JQ

**Comment by JMBeresford** [comment]
Ah, I misread. I assumed the web container was not accessible behind your reverse proxy.

The server address you are putting in the UI there needs to be accessible from the browser, as the browser is where the communication to the server originates from.

Presumably, your reverse proxy is giving you SSL/TLS between itself and the retrom-web container (when using the UI via the proxy, you have https:// rather than http:// in the browser url). You will not be able to connect to the retrom service via an insecure http connection from an established SSL/TLS session.

What @jquinn96 says is correct. Putting the service behind the proxy as they describe should make it accessible to your client while also behind the proxy.

**Comment by Toomblr** [comment]
You guys rock, thanks a lot. 
Putting server behind NPM and pointing towards the fqdn with port 443 fixed the issue.
